FROM docker.repo1.uhc.com/python:3.8

ENV PYTHONBUFFERED 1
ENV PYTHONPATH /backend

RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | POETRY_HOME=/opt/poetry python && \
    cd /usr/local/bin && \
    ln -s /opt/poetry/bin/poetry && \
    poetry config virtualenvs.create false

COPY ./prestart.sh ./pyproject.toml ./poetry.lock* /backend/

WORKDIR /backend

RUN poetry install
COPY . /backend
RUN pytest